### ISSUE TITLE
how to read a byte of the spd data from the dimm after 255(0xff) bytes?

### ISSUE THREAD

**Issue by Julyhcw** [zkemble/RAMSPDMod#1]
hi, can you tell me how to read a byte of the spd data from the DIMM after 255(0xff) bytes?
Thank you~

**Comment by ZakKemble** [comment]
This [post](https://www.raspberrypi.org/forums/viewtopic.php?p=190833&sid=3f0ebbd7a0324fb0ccec565a3723aee0#p190833) seems to suggest first using i2cset to set the address pointer then i2cget to read its value, which also causes the address pointer to automatically increment allowing you to use i2cget again to get the next byte. Just be careful when using i2cset, you don't want to accidentally write data and mess up your DIMM.
